# .gitlab-ci.yml
default:
  image: node:16

stages:
  - install
  - linting
  - test

install:
  stage: install
  script:
    - npm install
lint:
  stage: linting
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm run test
    - npm run test:e2e